services:
  aimg-server:
    container_name: aimg-server
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shared_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/stablestudio/generate || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  shared_net:
    external: true 