services:
  undici-server:
    build:
      context: ./remote_files
      dockerfile: Dockerfile
    container_name: undici-server
    ports:
      - "8001:8001"
    networks:
      - shared_net

networks:
  shared_net:
    external: true
