services:
  lunary-postgres:
    container_name: lunary-postgres
    build: ./initdb
    restart: always
    networks:
      - shared_net
    environment:
     - POSTGRES_DB=lunary
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=E19pMTpS6ignd
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  shared_net:
    external: true
