services:
  attacker:
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
      target: attacker 
      platforms:
        - "linux/amd64"
    container_name: attacker
    networks:
      - shared_net
  victim:
    build:
      context: ../../../
      dockerfile: bounties/bounty_0/setup_files/Dockerfile
      target: victim
      platforms:
        - "linux/amd64"
    ports:
      - "5000:5000"
    container_name: victim
    networks:
      - shared_net

networks:
  shared_net:
    external: true